/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as StockRouteImport } from './routes/stock'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PromosRouteImport } from './routes/promos'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OutletsRouteImport } from './routes/outlets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PromosRoute = PromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OutletsRoute = OutletsRouteImport.update({
  id: '/outlets',
  path: '/outlets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/categories': typeof CategoriesRoute
  '/customers': typeof CustomersRoute
  '/login': typeof LoginRoute
  '/outlets': typeof OutletsRoute
  '/products': typeof ProductsRoute
  '/promos': typeof PromosRoute
  '/reports': typeof ReportsRoute
  '/shifts': typeof ShiftsRoute
  '/stock': typeof StockRoute
  '/transactions': typeof TransactionsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/categories': typeof CategoriesRoute
  '/customers': typeof CustomersRoute
  '/login': typeof LoginRoute
  '/outlets': typeof OutletsRoute
  '/products': typeof ProductsRoute
  '/promos': typeof PromosRoute
  '/reports': typeof ReportsRoute
  '/shifts': typeof ShiftsRoute
  '/stock': typeof StockRoute
  '/transactions': typeof TransactionsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/categories': typeof CategoriesRoute
  '/customers': typeof CustomersRoute
  '/login': typeof LoginRoute
  '/outlets': typeof OutletsRoute
  '/products': typeof ProductsRoute
  '/promos': typeof PromosRoute
  '/reports': typeof ReportsRoute
  '/shifts': typeof ShiftsRoute
  '/stock': typeof StockRoute
  '/transactions': typeof TransactionsRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-insights'
    | '/categories'
    | '/customers'
    | '/login'
    | '/outlets'
    | '/products'
    | '/promos'
    | '/reports'
    | '/shifts'
    | '/stock'
    | '/transactions'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-insights'
    | '/categories'
    | '/customers'
    | '/login'
    | '/outlets'
    | '/products'
    | '/promos'
    | '/reports'
    | '/shifts'
    | '/stock'
    | '/transactions'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/ai-insights'
    | '/categories'
    | '/customers'
    | '/login'
    | '/outlets'
    | '/products'
    | '/promos'
    | '/reports'
    | '/shifts'
    | '/stock'
    | '/transactions'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiInsightsRoute: typeof AiInsightsRoute
  CategoriesRoute: typeof CategoriesRoute
  CustomersRoute: typeof CustomersRoute
  LoginRoute: typeof LoginRoute
  OutletsRoute: typeof OutletsRoute
  ProductsRoute: typeof ProductsRoute
  PromosRoute: typeof PromosRoute
  ReportsRoute: typeof ReportsRoute
  ShiftsRoute: typeof ShiftsRoute
  StockRoute: typeof StockRoute
  TransactionsRoute: typeof TransactionsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promos': {
      id: '/promos'
      path: '/promos'
      fullPath: '/promos'
      preLoaderRoute: typeof PromosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlets': {
      id: '/outlets'
      path: '/outlets'
      fullPath: '/outlets'
      preLoaderRoute: typeof OutletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiInsightsRoute: AiInsightsRoute,
  CategoriesRoute: CategoriesRoute,
  CustomersRoute: CustomersRoute,
  LoginRoute: LoginRoute,
  OutletsRoute: OutletsRoute,
  ProductsRoute: ProductsRoute,
  PromosRoute: PromosRoute,
  ReportsRoute: ReportsRoute,
  ShiftsRoute: ShiftsRoute,
  StockRoute: StockRoute,
  TransactionsRoute: TransactionsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
