/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KdsRouteImport } from './routes/kds'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KioskIndexRouteImport } from './routes/kiosk/index'
import { Route as ReceiptTransactionIdRouteImport } from './routes/receipt.$transactionId'
import { Route as KioskSuccessRouteImport } from './routes/kiosk/success'
import { Route as KioskMenuRouteImport } from './routes/kiosk/menu'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KdsRoute = KdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskIndexRoute = KioskIndexRouteImport.update({
  id: '/kiosk/',
  path: '/kiosk/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptTransactionIdRoute = ReceiptTransactionIdRouteImport.update({
  id: '/receipt/$transactionId',
  path: '/receipt/$transactionId',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskSuccessRoute = KioskSuccessRouteImport.update({
  id: '/kiosk/success',
  path: '/kiosk/success',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskMenuRoute = KioskMenuRouteImport.update({
  id: '/kiosk/menu',
  path: '/kiosk/menu',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/kds': typeof KdsRoute
  '/login': typeof LoginRoute
  '/kiosk/menu': typeof KioskMenuRoute
  '/kiosk/success': typeof KioskSuccessRoute
  '/receipt/$transactionId': typeof ReceiptTransactionIdRoute
  '/kiosk/': typeof KioskIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/kds': typeof KdsRoute
  '/login': typeof LoginRoute
  '/kiosk/menu': typeof KioskMenuRoute
  '/kiosk/success': typeof KioskSuccessRoute
  '/receipt/$transactionId': typeof ReceiptTransactionIdRoute
  '/kiosk': typeof KioskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/kds': typeof KdsRoute
  '/login': typeof LoginRoute
  '/kiosk/menu': typeof KioskMenuRoute
  '/kiosk/success': typeof KioskSuccessRoute
  '/receipt/$transactionId': typeof ReceiptTransactionIdRoute
  '/kiosk/': typeof KioskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/kds'
    | '/login'
    | '/kiosk/menu'
    | '/kiosk/success'
    | '/receipt/$transactionId'
    | '/kiosk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/kds'
    | '/login'
    | '/kiosk/menu'
    | '/kiosk/success'
    | '/receipt/$transactionId'
    | '/kiosk'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/kds'
    | '/login'
    | '/kiosk/menu'
    | '/kiosk/success'
    | '/receipt/$transactionId'
    | '/kiosk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  KdsRoute: typeof KdsRoute
  LoginRoute: typeof LoginRoute
  KioskMenuRoute: typeof KioskMenuRoute
  KioskSuccessRoute: typeof KioskSuccessRoute
  ReceiptTransactionIdRoute: typeof ReceiptTransactionIdRoute
  KioskIndexRoute: typeof KioskIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kds': {
      id: '/kds'
      path: '/kds'
      fullPath: '/kds'
      preLoaderRoute: typeof KdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk/': {
      id: '/kiosk/'
      path: '/kiosk'
      fullPath: '/kiosk/'
      preLoaderRoute: typeof KioskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$transactionId': {
      id: '/receipt/$transactionId'
      path: '/receipt/$transactionId'
      fullPath: '/receipt/$transactionId'
      preLoaderRoute: typeof ReceiptTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk/success': {
      id: '/kiosk/success'
      path: '/kiosk/success'
      fullPath: '/kiosk/success'
      preLoaderRoute: typeof KioskSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk/menu': {
      id: '/kiosk/menu'
      path: '/kiosk/menu'
      fullPath: '/kiosk/menu'
      preLoaderRoute: typeof KioskMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  KdsRoute: KdsRoute,
  LoginRoute: LoginRoute,
  KioskMenuRoute: KioskMenuRoute,
  KioskSuccessRoute: KioskSuccessRoute,
  ReceiptTransactionIdRoute: ReceiptTransactionIdRoute,
  KioskIndexRoute: KioskIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
